-- 챌린지 직접 관리: 챌린지명 + 게시판 URL + 참여 명단 입력 (관리자)
-- 게시판은 20HA와 동일한 네이버 카페 게시판 형식

-- 1) challenges 컬럼 추가: 게시판 URL 원문 + 카페 club id
ALTER TABLE public.challenges ADD COLUMN IF NOT EXISTS board_url     text;
ALTER TABLE public.challenges ADD COLUMN IF NOT EXISTS naver_cafe_id text DEFAULT '31045190';

-- 2) 참여 명단 테이블
CREATE TABLE IF NOT EXISTS public.challenge_participants (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_key text NOT NULL REFERENCES public.challenges(key) ON DELETE CASCADE,
  name          text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (challenge_key, name)
);
ALTER TABLE public.challenge_participants ENABLE ROW LEVEL SECURITY;

-- 3) RPC: 챌린지 추가/수정 (관리자)
CREATE OR REPLACE FUNCTION public.upsert_challenge(
  p_key text, p_name text, p_board_url text,
  p_cafe_id text, p_board_menu_id text, p_active boolean
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  INSERT INTO public.challenges (key, name, board_url, naver_cafe_id, naver_board_id, active, sort_order)
  VALUES (
    p_key, p_name, p_board_url,
    COALESCE(NULLIF(p_cafe_id, ''), '31045190'),
    NULLIF(p_board_menu_id, ''),
    COALESCE(p_active, true),
    COALESCE((SELECT max(sort_order) + 1 FROM public.challenges), 1)
  )
  ON CONFLICT (key) DO UPDATE SET
    name          = EXCLUDED.name,
    board_url     = EXCLUDED.board_url,
    naver_cafe_id = EXCLUDED.naver_cafe_id,
    naver_board_id= EXCLUDED.naver_board_id,
    active        = EXCLUDED.active;
END; $$;

-- 4) RPC: 챌린지 삭제 (관리자) — 글/명단 CASCADE
CREATE OR REPLACE FUNCTION public.delete_challenge(p_key text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  DELETE FROM public.challenges WHERE key = p_key;
END; $$;

-- 5) RPC: 명단 일괄 설정 (관리자) — 기존 명단 교체
CREATE OR REPLACE FUNCTION public.set_challenge_participants(p_key text, p_names text[])
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  DELETE FROM public.challenge_participants WHERE challenge_key = p_key;
  INSERT INTO public.challenge_participants (challenge_key, name)
  SELECT p_key, trim(n) FROM unnest(p_names) AS n WHERE trim(n) <> ''
  ON CONFLICT (challenge_key, name) DO NOTHING;
END; $$;

-- 6) RPC: 명단 조회
CREATE OR REPLACE FUNCTION public.get_challenge_participants(p_key text)
RETURNS SETOF public.challenge_participants
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT * FROM public.challenge_participants WHERE challenge_key = p_key ORDER BY name;
$$;
