-- 챌린지 관리 (관리자 전용) — 학생 아이디와 무관, 인증글 크롤링 + 확인 체크만
-- 챌린지 종류: 사고력 영작 / 독서챌린지 / 수학독해 챌린지
-- 참여 명단·회차별 마감은 추후 입력 (틀만 구성)

-- 1) 챌린지 설정 테이블
CREATE TABLE IF NOT EXISTS public.challenges (
  key            text PRIMARY KEY,           -- 'sagoyeong' | 'reading' | 'mathread'
  name           text NOT NULL,
  naver_board_id text,                        -- 네이버 카페 게시판 menu id (나중에 입력)
  sort_order     int  NOT NULL DEFAULT 0,
  active         boolean NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.challenges ENABLE ROW LEVEL SECURITY;

INSERT INTO public.challenges (key, name, sort_order) VALUES
  ('sagoyeong', '사고력 영작',   1),
  ('reading',   '독서챌린지',     2),
  ('mathread',  '수학독해 챌린지', 3)
ON CONFLICT (key) DO NOTHING;

-- 2) 챌린지 인증글 (크롤링 결과 + 선생님 확인 체크)
CREATE TABLE IF NOT EXISTS public.challenge_posts (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_key  text NOT NULL REFERENCES public.challenges(key) ON DELETE CASCADE,
  naver_nickname text,
  post_title     text,
  post_url       text NOT NULL,
  posted_at      timestamptz,
  crawled_at     timestamptz NOT NULL DEFAULT now(),
  parsed_name    text,            -- 제목에서 추출한 이름 (best-effort)
  parsed_round   int,             -- 제목에서 추출한 회차 (best-effort)
  checked        boolean NOT NULL DEFAULT false,  -- 선생님이 글 보고 확인함
  checked_at     timestamptz,
  UNIQUE (challenge_key, post_url)
);
ALTER TABLE public.challenge_posts ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_challenge_posts_key
  ON public.challenge_posts (challenge_key, posted_at DESC);

-- 3) RPC: 챌린지 목록
CREATE OR REPLACE FUNCTION public.get_challenges()
RETURNS SETOF public.challenges
LANGUAGE sql SECURITY DEFINER
SET search_path = public
AS $$
  SELECT * FROM public.challenges ORDER BY sort_order, name;
$$;

-- 4) RPC: 특정 챌린지의 인증글 목록
CREATE OR REPLACE FUNCTION public.get_challenge_posts(p_challenge_key text, p_limit int DEFAULT 500)
RETURNS SETOF public.challenge_posts
LANGUAGE sql SECURITY DEFINER
SET search_path = public
AS $$
  SELECT * FROM public.challenge_posts
  WHERE challenge_key = p_challenge_key
  ORDER BY posted_at DESC NULLS LAST, id DESC
  LIMIT p_limit;
$$;

-- 5) RPC: 확인 체크 토글 (관리자만)
CREATE OR REPLACE FUNCTION public.toggle_challenge_check(p_post_id bigint, p_checked boolean)
RETURNS void
LANGUAGE sql SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.challenge_posts
  SET checked    = p_checked,
      checked_at = CASE WHEN p_checked THEN now() ELSE NULL END
  WHERE id = p_post_id
    AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin');
$$;
