-- 챌린지 회차별 마감일
CREATE TABLE IF NOT EXISTS public.challenge_rounds (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_key text NOT NULL REFERENCES public.challenges(key) ON DELETE CASCADE,
  round_no      int  NOT NULL,
  deadline      date,
  UNIQUE (challenge_key, round_no)
);
ALTER TABLE public.challenge_rounds ENABLE ROW LEVEL SECURITY;

-- 게시판 타입(L/I 등) 저장 컬럼 (네이버 게시판 boardtype)
ALTER TABLE public.challenges ADD COLUMN IF NOT EXISTS naver_board_type text DEFAULT 'L';

-- 회차 조회
CREATE OR REPLACE FUNCTION public.get_challenge_rounds(p_key text)
RETURNS SETOF public.challenge_rounds
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT * FROM public.challenge_rounds WHERE challenge_key = p_key ORDER BY round_no;
$$;

-- 회차 일괄 설정 (관리자) — jsonb 배열 [{"round":1,"deadline":"2026-06-07"}, ...]
CREATE OR REPLACE FUNCTION public.set_challenge_rounds(p_key text, p_rounds jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'not authorized';
  END IF;
  DELETE FROM public.challenge_rounds WHERE challenge_key = p_key;
  INSERT INTO public.challenge_rounds (challenge_key, round_no, deadline)
  SELECT p_key,
         (r->>'round')::int,
         NULLIF(r->>'deadline','')::date
  FROM jsonb_array_elements(COALESCE(p_rounds, '[]'::jsonb)) AS r
  WHERE (r->>'round') IS NOT NULL
  ON CONFLICT (challenge_key, round_no) DO UPDATE SET deadline = EXCLUDED.deadline;
END; $$;
